// simple base64 en/decoding from http://stackoverflow.com/questions/342409/how-do-i-base64-encode-decode-in-c
#ifndef _BASE64_H_
#define _BASE64_H_

#include <stdint.h>
#include <stdlib.h>
/** check wether a character is base64 or not
 * @c character to test
 * @return 1 if c is base64, 0 if not
 * */
int base64_isbase64(char c);

/** Encode some data to a base64 encoded string
 * @data pointer to the data to encode
 * @input_length length of the input data
 * @output_length pointer where to store length of the output data
 * @return a pointer to the encoded string
 * */
char *base64_encode(const unsigned char *data,
                    size_t input_length,
                    size_t *output_length);

/** Decodes a base64 encode string
 * @data pointer to the data to decode
 * @input_length length of the input data
 * @output_length pointer where to store the length of the output data
 * @return a pointer to the decoded data
 * */
unsigned char *base64_decode(const char *data,
                             size_t input_length,
                             size_t *output_length);

/** Cleans up the decoding tables generated by this module
 */
void base64_cleanup();

#endif
